name: DevSecOps SAST Pipeline
on:
  push:
    branches:
      - main
jobs:
  sonarcloud-scan:
    name: Run Sonar Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        # 1. This fixes the yellow warning you saw:
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # 2. This fixes the Exit Code 3 error:
          args: >
            -Dsonar.organization=ramchanderram
            -Dsonar.projectKey=RamchanderRam_devsecops-sast-demo
